### ISSUE TITLE
Brainstorm ways to make Client constructor easier to use

### ISSUE THREAD

**Issue by Vishwa-Mozilla** [Vishwa-Mozilla/remote-settings-client#19]
**Motivation:** Currently Client constructor at least expects a collection name and a verification logic or None but we want to brainstorm other ways where user does not have to provide None in the Client to signify using Default Verification

**Comment by leplatrem** [comment]
Please share here what existing libraries do (eg. Redis, postgreSQL, ...).

What about something like that?

```rust
let mut client = Client::create("collection-name".to_owned());
client.set_verifier(CustomVerifier{});
client.set_server(Server::STAGE);
```

Please present some snippets, and comment their pros / cons

**Comment by leplatrem** [comment]
What about this?

```rust
let client = Client.create("collection-name", &ClientOptions::default());
```
or

```rust
let client = Client.create("collection-name", &ClientOptions{
  verifier: &CustomVerifier(),
  ...ClientOptions::default()
});
``
?

**Comment by Vishwa-Mozilla** [comment]
I really like the idea of a ClientBuilder to customize your Client that reqwest is using - https://docs.rs/reqwest/0.9.4/reqwest/struct.ClientBuilder.html

**Comment by Vishwa-Mozilla** [comment]
this way we can simplify the constructor and allow the user to pick and choose whatever they want

**Comment by Vishwa-Mozilla** [comment]
**Approach 1:** Create a ClientBuilder that configures remote settings client construction
Supporting evidence for the Builder Pattern approach: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
   - Differentiates between Non-Consuming (preferred) and Consuming Builders
   - Redis using Builder pattern for ClusterClient - https://github.com/mitsuhiko/redis-rs/blob/master/src/cluster.rs

**Pros:** 
- Easier for the user than to scroll through all the different functions based on the fields they want to override
- A cleaner API than what we have currently (existing repos use it and Rust docs also mention its use for constructing complex structs) 
**Cons:**
- User has to learn to use the Builder 

**Approach 2:** ...Default::default() approach 

Since we have already implemented the Default() trait for Client, we can let clients choose what they want to override and for the rest of the fields, just pass ...Default::default()

For example, if they just want to override server_url, 

 let client = Client {
        collection_name: "url-classifier-skip-urls".to_owned(),
        ..Default::default()
 };

**Pros:**
Very easy for the user to create Client, no need to learn to use any other struct to configure the client, and code will be very simple - also less work!
**Cons:**
- Make fields public for the user to access them
- We can make only certain fields public (gives us control over which fields a user can override

**Approach 3:** Stick with the current approach with different functions for different configurations
Seen in Postgres and Redis clients where there are numerous methods for establishing a connection (but it does not exactly match our use-case since establishing a connection has way more options than few fields in our case)

**Pros:**
- Avoid doing extra work
**Cons:**
- API could get messy with the introduction of new fields (harder for the user to keep up)

My personal take: Approach 2 (Best) > Approach 1 (Better) > Approach 3 (Ok)
Reasons: Simpler API is very important; also if we can achieve that with less work - why not?

**Comment by Vishwa-Mozilla** [comment]
@leplatrem let me know what you think of the above approaches and please share if you have another one in mind

**Comment by leplatrem** [comment]
I think that *approach 2* has an issue: it does not enforce the passing of a collection name, which is the only mandatory parameter. 

That's why I was proposing the introduction of a ClientOptions struct for the optional values only.
https://github.com/Vishwa-Mozilla/remote-settings-client/issues/19#issuecomment-653561786

Otherwise I'd definitely prefer *approach 1*

**Comment by ncalexan** [comment]
> I think that _approach 2_ has an issue: it does not enforce the passing of a collection name, which is the only mandatory parameter.

In my experience, approach 1 scales better than 2.

**Comment by Vishwa-Mozilla** [comment]
alright, will take approach 1
