### ISSUE TITLE
Inject Verifier into the Remote Settings Client

### ISSUE THREAD

**Issue by Vishwa-Mozilla** [Vishwa-Mozilla/Remote-Settings-Client#2]
**Motivation:** Enable users of Remote Settings Client to pass verifier as a dependency and if not provided, the client falls back to the default implementation - OpenSSL. This enhancement allows for custom verifier logic to be injected into the Remote Settings Client if users have their own implementation for signature verification. Include Unit testing along with the change.

**Comment by mostlygeek** [comment]
AFIAK there are two crypto libraries that we want to support ([NSS](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS)) and openssl.  Is this to implement an abstraction layer for those two libraries so the rest of the code does not need to care about the implementation just the interface?

**Comment by Vishwa-Mozilla** [comment]
@mostlygeek yes
