### ISSUE TITLE
Cover canonical JSON corner cases 

### ISSUE THREAD

**Issue by leplatrem** [Vishwa-Mozilla/remote-settings-client#21]
See https://github.com/leplatrem/rs-client.rs/issues/4 and https://github.com/leplatrem/rs-client.rs/issues/3

**Comment by Vishwa-Mozilla** [comment]
Python implementation: https://github.com/Kinto/kinto-signer/blob/master/kinto_signer/canonicaljson.py  Tests: https://github.com/Kinto/kinto-signer/blob/master/tests/test_canonicaljson.py 
https://github.com/matrix-org/python-canonicaljson/pull/17
Javascript https://searchfox.org/mozilla-central/source/toolkit/modules/CanonicalJSON.jsm 
Tests: https://searchfox.org/mozilla-central/source/toolkit/modules/tests/xpcshell/test_CanonicalJSON.js
